### ISSUE TITLE
MLP jobs can raise an error when launched in a multi-threading mode

### ISSUE THREAD

**Issue by tomdemeyere** [Quantum-Accelerators/quacc#1641]
### Details about the quacc environment

- **quacc version**: 0.6.2
- **Python version**: 3.11.7

### What is the issue?

``` python

config = Config(
    executors=(
        ThreadPoolExecutor(
            max_threads=64,
        ),
    ),
    app_cache=False

```

With a for loop over jobs will lead to a weird error: "raise NameError("module is not installed as a submodule")".  (torch/fx/_symbolic_trace.py:441)

``` python

      for n, atoms in enumerate(atoms_list):
          time.sleep(n*10).  <--- Adding this solve the issue.
          results = mace_relax_job(atoms)
          write_to_db(results)
          all_results.append(results)

```

I cannot reproduce the issue on all my machines, my M1 does it *sometimes* while HPC will do it all the time.

### How can we easily reproduce the issue?

```python
mace_relax_job = partial(
    relax_job,
    method="mace",
    model="large",
    device="cpu",
    opt_params={"optimizer": SciPyFminBFGS, "fmax": 0.1},
)
@flow
def workflow(atoms_list):

    @subflow
    def relax_atoms_list(atoms_list):
        all_results = []

        for n, atoms in enumerate(atoms_list):
            all_results.append(mace_relax_job(atoms))

        return all_results

    relaxed = relax_atoms_list(atoms_list)

    return relaxed


atoms_list = [molecule("H2O") for i in range(128)]

futures = workflow(atoms_list)
```

**Comment by Andrew-S-Rosen** [comment]
Thanks for the report!

## Unsolicited Advice

First, I will note that you can most likely simplify your situation here (I'm not sure how much was abstracted away for the issue report, so maybe this won't be relevant for you). The `@subflow` decorator is really only necessary if you are launching a dynamic job where the number of jobs is not known _a priori_. At least here, that value is known (maybe it is not known in practice though). The `@flow` decorator also doesn't do anything with Parsl, just as a head's up.

The above example could likely be done as follows, like shown in [the docs](https://quantum-accelerators.github.io/quacc/user/wflow_engine/executors2.html):

```python
from concurrent.futures import as_completed

from ase.build import molecule
from ase.optimize.sciopt import SciPyFminBFGS
from quacc.recipes.mlp.core import relax_job
from tqdm import tqdm

atoms_list = [molecule("H2O") for i in range(128)]
futures = []

for atoms in atoms_list:
    future = relax_job(
        atoms,
        method="mace",
        model="large",
        device="cpu",
        opt_params={"optimizer": SciPyFminBFGS, "fmax": 0.1},
    )
    futures.append(future)


for future in tqdm(as_completed(futures), total=len(futures)):
    task_doc = future.result()
    print(task_doc)
```

Of course, I don't know the context, so maybe you're already aware and this is irrelevant for you.

## The Issue

I am going to make a guess here of what's going on, which could certainly be wrong. In your scenario, you are running in multi-threaded mode where multiple Python processes are being launched on a compute core. Looking at the culprit in [pytorch](https://github.com/pytorch/pytorch/blob/2327879fb6fe3836a9be0bca18e6442d07c04900/torch/fx/_symbolic_trace.py#L429), it seems to be a method that is doing some filesystem crawling. My hunch is that one process on the compute core is changing the current working directory (e.g. in `calc_setup` or `calc_cleanup`) in the midst of PyTorch crawling the filesystem in the other, concurrent process (since threads on the same compute core share a common working directory). Unfortunately, at this time, there is no way to remove the `os.chdir` calls in `calc_setup` and `calc_cleanup` because not all ASE calculators currently respect their `directory` keyword argument, so we have to `cd` into the necessary directory as a precaution to ensure the calculations are run in the correct place.

If you are running a compute node with, say, 32 physical cores each of which has 2 hardware threads, I would recommend that your quacc calculations run on all 32 physical cores but only one thread each. That is the distinction between physical cores (32) and logical cores (64). This does mean that the `ThreadPoolExecutor` would potentially not be the executor of choice in this scenario since that executor is meant for multi-threading (e.g. if you set `max_threads = 2`, it will distribute work over two threads on the same compute core, not two separate compute cores). It would likely be better to figure out how to distribute the work over the physical cores on a node via the `HighThroughputExecutor` in the context of Parsl.

**Comment by tomdemeyere** [comment]
Thanks for this descriptive answer, the code I have posted is indeed part of a bigger workflow. Also I like to use @subflow because they resolve list of futures automatically. In any case, your example is nice because it reminds me that using @flow is always optional.

I thought about using the HighThroughputExecutor but as you mentioned on the Parsl stack (thanks for asking there btw) I didn't think of using it for multiple Apps on the same node! It seems that it is totally doable and it's probably a much cleaner option.

After having a quick look at the code after the grid_phonon_flow catastrophe I thought that all cd's were removed from quacc (I can see them now), I will think twice before using Threads like a savage.

**Comment by Andrew-S-Rosen** [comment]
> I thought about using the HighThroughputExecutor but as you mentioned on the Parsl stack (thanks for asking there btw) I didn't think of using it for multiple Apps on the same node! It seems that it is totally doable and it's probably a much cleaner option.

Yup, it should be! In fact, I imagine this is a pretty common use case for both Parsl and Dask users. I haven't done it myself though.

> After having a quick look at the code after the grid_phonon_flow catastrophe I thought that all cd's were removed from quacc (I can see them now), I will think twice before using Threads like a savage.

Sadly not! I was able to get rid of all instances of relative file paths causing issues, but I ultimately couldn't remove the `cd` calls. Too many broken things upstream in ASE at the moment, and not much I can do without involvement from those above me... :(

Threads are definitely a "go at your own risk" approach for now!

**Comment by tomdemeyere** [comment]
Coming back on your suggestions, right now I am writing a workflow which is 3 steps:

1. Relax base structures
2. Construct alloys based on them
3. Relax the alloys

The alloy construct part is nothing fancy, a few numpy operations, although the input depends on a future (relaxed base structure)

What is the recommended best practice in this case?

- construct_alloy function should be a `@job` in the workflow because it takes futures as input and it does a simple operation which do not call other `@job`.
- I should first resolve the futures from the first relax and then send this to a simple non-`@job` construct_alloy function.

Also, my mental representation is that my whole workflow should be located into a `@flow` but I don't know if that's necessary really.

**Comment by Andrew-S-Rosen** [comment]
This is essentially the same thing as the [Running a User-Constructed Dynamic Workflow](https://quantum-accelerators.github.io/quacc/user/wflow_engine/wflow_engines2.html#running-a-user-constructed-dynamic-workflow) example in the documentation, which has: 1) relax a base structure; 2) Construct slabs from them; 3) Relax the slabs. So, you can likely refer to that example and the underlying functions for the structure. 

There are many ways to achieve this goal, but the most efficient is probably something like this:

1. Make a `@flow`. Let's call it `alloy_flow` here for the sake of clarity. With Parsl, the `@flow` decorator does not have any function, but we'll include it anyways for full compatibility with other workflow engines.
2. This `alloy_flow` will call two functions: a) a `relax_job` `@job` function to relax the input structure; b) a `@subflow` that will generate the alloys and do a relax on each. Parsl will know to resolve Futures automatically if given as inputs, so you can pass in the `output["atoms"]` of job "a" to the input of "job" b without calling a blocking `.result()`.
3. The `relax_job` is fairly self-explanatory. The `@subflow` coming after will look almost exactly the same as [`bulk_to_slabs_subflow`](https://github.com/Quantum-Accelerators/quacc/blob/main/src/quacc/recipes/common/slabs.py#L18). In essence, you'll have a function in there that will generate alloys, and then you'll use a `for` loop over each to call individual relax jobs, and you'll return a `list[RunSchema]`.

> construct_alloy function should be a @job in the workflow because it takes futures as input and it does a simple operation which do not call other @job.

You certainly could do this if you chose to. But if you wanted to save a dispatched job, you could pack this into the `@subflow`, which will automatically resolve the input future for you.

> I should first resolve the futures from the first relax and then send this to a simple non-@job construct_alloy function.

In general, it is wise to avoid any blocking calls in the intermediate steps of the workflow to ensure full concurrency is achieved. The above example should make that possible.

> Also, my mental representation is that my whole workflow should be located into a @flow but I don't know if that's necessary really.

Recommended but not strictly necessary for Parsl.

**Comment by tomdemeyere** [comment]
Thanks for all the advice, this is actually really helpful. I will probably copy that somewhere since I end up coming back to it a lot 😅
