### ISSUE TITLE
ValueError: Charge of 0 and spin multiplicity of 1 is not possible for this molecule.

### ISSUE THREAD

**Issue by tomdemeyere** [Quantum-Accelerators/quacc#1645]
### Details about the quacc environment

- **quacc version**: 0.6.3
- **Python version**: 3.11.7

### What is the issue?

With a forcefield this will always happen if the system contains an odd number of electrons?

quacc/atoms/core.py", line 191, in check_charge_and_spin

### How can we easily reproduce the issue?

```python
# Paste your *minimal* example code here
```

**Comment by Andrew-S-Rosen** [comment]
Thanks for the report. Can you please provide some more details about how you are getting this error in a given calculation? Some additional context would be helpful. I'm aware of why the error is being raised, but it's not yet clear to me how this would come up in a practical scenario.

Let's consider O2:

```python
from ase.build import molecule
from quacc.recipes.lj.core import static_job

atoms = molecule("O2")
atoms.set_initial_magnetic_moments([1.0, 1.0])
static_job(atoms)
```

This works and is charge = 0, spin multiplicity = 3.

Now let's try O2-, superoxide which has an odd number of electrons.

```python
atoms = molecule("O2")
atoms.set_initial_magnetic_moments([1.0, 0.0])
atoms.set_initial_charges([-1.0, 0.0])
static_job(atoms)
```

That works. However, just doing `atoms.set_initial_magnetic_moments([1.0, 0.0])` would not work because it's impossible to have O2* neutrally charged.

Some additional context would be beneficial.

**Comment by tomdemeyere** [comment]
``` python
atoms = Octahedron("Pt", 3, 1)
atoms[0].symbol = "Au"

static_job(atoms, model="large", method="mace")
```

**Comment by Andrew-S-Rosen** [comment]
The charge and spin multiplicity _should_ only be reported in the output schema (and therefore checked for internal consistency by quacc) if the structure lacks periodic boundary conditions. Here, your structure is an isolated cluster with no PBCs. If you were to throw that into a molecular DFT program like Gaussian, ORCA, or Q-Chem, it would error out for the same reason. Is there a reason why you do not have PBCs enabled for this system, not even a vacuum box?

**Comment by tomdemeyere** [comment]
Indeed setting pbc to True avoid the issue! I am not sure if this is mentioned in the doc, if it is sorry for the inconvenience.

This behaviour might surprise careless users, I only see one case where this will fail: running these kind of clusters with martyna-turckerman on (pbc set to False) but I guess this is somewhat of a niche case

**Comment by Andrew-S-Rosen** [comment]
Thanks for investigating. This wasn't mentioned in the docs because, I must admit, it wasn't a scenario I had thought about.

Basically, what is happening behind the scenes is that quacc is trying to make metadata for the Atoms object. It does this by converting it to a Pymatgen `Structure` or `Molecule` object, for which we have detailed routines to generate all the metadata. If the `Atoms` object has no PBCs, it's assumed to be a `Molecule` (since `Structure` is for materials with a lattice). In generating the `Molecule` metadata, it reports (and checks) various molecular properties like the charge and spin multiplicity. Here, if you passed your cluster into a molecular DFT program with charge = 0, spin multiplicity = 1, it would fail, and quacc does the same. But here you are at an awkward edge case where you aren't running a molecular DFT calculation but the structure itself lacks PBCs so it's being treated like a molecule.

I'll do some digging to see if/how I can ensure spurious errors aren't raised while also making sure the metadata for the molecular DFT folks continues to be generated correctly.

**Comment by tomdemeyere** [comment]
I have seen a check_metal function somewhere, if it’s a metal quacc does not check? it’s not perfect but will surely help?

**Comment by Andrew-S-Rosen** [comment]
I'd prefer to address the problem at its source. Not to worry. I'll sort it out in #1646, almost certainly.
