### ISSUE TITLE
Phonon flow does not work with MACE-MP-0 when `dispersion=True`

### ISSUE THREAD

**Issue by tomdemeyere** [Quantum-Accelerators/quacc#1652]
### Details about the quacc environment

- **quacc version**: 0.6.4
- **Python version**: 3.11.7

### What is the issue?

When sending a static job into the common phonon_flow it will not necessarily compute the forces, which will lead you right into: forces = [output["results"]["forces"] for output in force_job_results]

This is because inside static_jobs, only .get_potential_energy() is called.

### How can we easily reproduce the issue?

```python
mace_force_job = partial(
    static_job,
    method="mace",
    model="large",
    default_dtype="float32",
    device="cpu",
    dispersion=True,
)

atoms = molecule("H2O", vacuum=10)

results = phonon_flow(
    atoms,
    force_job=mace_force_job,
    min_length=None,
    phonopy_kwargs={"supercell_matrix": [1, 1, 1]},
)
```

Something else unrelated: I had to change the flow a little bit to allow passing `phonopy_kwargs={"supercell_matrix": [1, 1, 1]}` min_length is nice but often full control over q-points is needed. min_length is problematic in case of a slab for example.

**Comment by Andrew-S-Rosen** [comment]
I will add the `supercell_matrix` kwarg back in. It used to be present, but I replaced it in favor of `min_length`. I will include both options in an update. That said, I don't think it is problematic for a slab. If you want the `min_length` to be 10 A, then the c dimension with vacuum would not be expanded to a supercell (assuming the slab + total vacuum space is at least 10 A). Could you explain a bit why it would be problematic for a slab? 

As for the force issue, by design, a `@job` that computes forces is meant to be passed. That said, the behavior you receive is odd. [I have small but existent tests](https://github.com/Quantum-Accelerators/quacc/blob/main/tests/core/recipes/mlp_recipes/test_phonon_recipes.py) for the MLP phonon recipe, and it passes. I wonder if it's that the MACE model is not parsing/computing forces or a non-PBC structure? I will have to investigate later.

**Comment by tomdemeyere** [comment]
For the slab, say c is ~ 15 Å and a, b are ~ 6 Å, now you want the supercell to be [3, 3, 1], in this case you should pass min_length = 18, which will results in [3, 3, 2] ? I am possibly completely mistaken as well

Also, I didn't explicitly say it: I am using the common.phonon flow not the mlp one but it should not matter I think 

Changing pbc does not seems to have any impact, replacing atoms.get_potential_energy() to get_forces() in the runner fix the issue

**Comment by Andrew-S-Rosen** [comment]
> For the slab, say c is ~ 15 Å and a, b are ~ 6 Å, now you want the supercell to be [3, 3, 1], in this case you should pass min_length = 18, which will results in [3, 3, 2] ? I am possibly completely mistaken as well

That is fair. I'll update it to be `min_lengths: float | tuple[float, float, float] | None` to allow for more flexibility. 

Will report back on the forces issue when I get to that later today.

**Comment by Andrew-S-Rosen** [comment]
As for the MLP issue, that is due to an upstream issue in MACE: https://github.com/ACEsuit/mace/issues/315. I'd prefer it to get solved there.

**Comment by tomdemeyere** [comment]
Thanks for taking care of that!

**Comment by Andrew-S-Rosen** [comment]
Did not mean to close.
