### ISSUE TITLE
Add a non-SCF job for VASP

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [Quantum-Accelerators/quacc#1774]
### What new feature would you like to see?

Ideally, we should take some inspiration from the typical MP non-SCF workflow in [atomate2](https://github.com/materialsproject/atomate2/blob/e9fe5c27a4a9d24a90d964964d5fe809aa78d5f0/src/atomate2/vasp/sets/core.py#L168) as well in terms of settings.

**Comment by yw-fang** [comment]
Since I inquired about the feature of non-SCF job for VASP several days ago and no one others are working on it, I implemented a little bit about it 1b4ab8e217ae85127bff6f25fbe6dee66f58bd09
I still need some time to further meet the guidelines of code contributions if @Andrew-S-Rosen thinks this implementation looks not so bad

**Comment by Andrew-S-Rosen** [comment]
Thanks for the comment and your effort, @yw-fang! It is definitely a solid start. Should it be of interest to you, I would be happy to provide initial comments and feedback on it if you decide to open a PR. Most of the content is there; it just requires some cleanup of things.
