### ISSUE TITLE
Unexpected scratch subdirectory behavior when the path is relative

### ISSUE THREAD

**Issue by yw-fang** [Quantum-Accelerators/quacc#1858]
### Details about the quacc environment

- **quacc version**: 0.6.11 and 0.6.10
- **Python version**: 3.9.18

### What is the issue?

I noticed this issue during the implementation of the nscf_job https://github.com/Quantum-Accelerators/quacc/pull/1840 

Because I have set up two virtual environment. 
One is py39 and another py39_develop.

In the py39, the version 0.6.7 of quacc was installed. After the static calculations, all files in $SCRATCH could be removed as expected. 
In the py39_develop, the quacc code was updated in line with the latest commitment (v0.6.11), I found there was always another $SCRATCH located in $SCRATCH. I found this issue has already existed in the released version 0.6.10.

### How can we easily reproduce the issue?

```python
from quacc.recipes.vasp.core import static_job
results = static_job(atoms, copy_files=None, **static_kwargs)
```

**Comment by Andrew-S-Rosen** [comment]
Thank you for the report, @yw-fang. File handling was completely overhauled in 0.6.8, so it is certainly possible that there was a bug not caught by our test suite.

I could use a little bit of additional information to understand the issue you're reporting. I don't quite follow what you mean when you say "there was always another $SCRATCH located in $SCRATCH". Would you be able to clarify so that I can pinpoint the bug and make a patch?

For instance, I did the following:

```bash
quacc set SCRATCH_DIR ~/
```

```python
from quacc.recipes.emt.core import relax_job
from ase.build import bulk

atoms = bulk("Cu")*(100,10,10)
relax_job(atoms)
```

and found that the `SCRATCH_DIR` was empty (as expected) when the run was completed. I'm trying to reproduce the issue you're seeing.

**Comment by yw-fang** [comment]
Hi, @Andrew-S-Rosen thanks for your quick response. 

The .quacc.yaml file includes in the HPC I am using:
```
SCRATCH_DIR: $SCRATCH
CREATE_UNIQUE_DIR: false
```

Because $SCRATCH is actually not predefined in my HPC, `echo $SCRATCH` in shell terminal is None. In this case, the quacc creates $SCRATCH in the directory I submitted the job (feel free to criticize me if it's not a good matter when using quacc)

Now let's show the test results with EMT and VASP.

# EMT toy calculations
Using the emt example you showed above, $SCRTCH was empty as your test.

# VASP toy calculations
But in the case of vasp job, e.g.
```
from quacc.recipes.vasp.core import static_job
from ase.build import bulk

atoms = bulk("Cu")
static_kwargs={
    'encut': 300,
    'ediff': 1.e-3,
    'pmg_kpts': {'kppvol': 10},
    'ismear': 1,
    'ispin': 1,
    }

static_job(
        atoms,
        **static_kwargs
        )
```
Once calculations done, $SCRATCH in the directory I ran the calculations was not empty, it contains a subfolder with the same name $SCRATCH which didn't contain anything. 

If the description is still confusing, let me know about it. Thanks very much!

**Comment by Andrew-S-Rosen** [comment]
Thanks for the additional details!

> Because $SCRATCH is actually not predefined in my HPC, echo $SCRATCH in shell terminal is None. In this case, the quacc creates $SCRATCH in the directory I submitted the job (feel free to criticize me if it's not a good matter when using quacc)

Ah, that was just a demonstrative example in the documentation. If you don't have a `$SCRATCH` environment variable, you can simply choose whatever directory you'd like, e.g. `/path/to/my/favorite/scratch/dir`. I clarified the docs on this point.

As for the actual issue reported here, I will test it out right now with VASP. Thanks!

**Comment by yw-fang** [comment]
Thanks for changing the subject into a gentle style  :sweat_smile:, and the clarification about SCRATCH_DIR.

**Comment by Andrew-S-Rosen** [comment]
@yw-fang: I believe the behavior is occurring because your `SCRATCH_DIR` is a _relative_ file path. If you try with an absolute path, I don't think you will see this behavior. At least, I am not able to reproduce the behavior if I use an absolute path.

To resolve this, I will have `quacc` raise a warning if the path is relative so the user knows.

If you still see the issue after using an absolute path, please let me know.

**Comment by yw-fang** [comment]
Hello, @Andrew-S-Rosen  Thanks for implementing the ValueErroe.
I tested the VASP calculations including static_job and nscf_job using an absolute path for SCRATCH_DIR, and didn't find any errors. Thanks!

**Comment by Andrew-S-Rosen** [comment]
Great to hear!
