### ISSUE TITLE
MP GGA VASP workflows resort and cause problems with per-atom defaults like LDA+U

### ISSUE THREAD

**Issue by zulissimeta** [Quantum-Accelerators/quacc#2583]
### Details about the quacc environment

- **quacc version**: latest
- **Python version**: 3.11

### What is the issue?

The ASE Vasp calculator resorts the atoms when writing POSCARs, which is a problem when any specific script (like the scripts to guess MP-like LDA+U or magmom settings). 

This is a problem because using the mp_gga_relax_job will silently cause problems if the input atoms object does not have the same order as what the Vasp calculator will plan to do. See the script below for the minimum reproducible example. Running the MP GGA relax jobs on atoms objects with random sorting and LDAU settings will also have problems, but the calculator won't actually throw errors as VASP will just ignore more LDA+U parameters than the number of species. 

### How can we easily reproduce the issue?

```python
from quacc.calculators.vasp import Vasp
from ase import Atoms
atoms = Atoms('HOH', cell=[10,10,10])
atoms.set_calculator(Vasp(atoms, ldau=True, ldauu=[1,2,3]))
atoms.calc.write_input(atoms)
```

Notice that in this example, INCAR has LDAUU=[1,2,3], while the POSCAR has been resorted to not be HOH but instead be H2O, so that there are only two species.

**Comment by Andrew-S-Rosen** [comment]
@zulissimeta: Well, this isn't fun. I definitely believe there may be a problem, but I think I need a few more details to fully understand the specific issue and how to fix it. I have run so many checks to verify there are no resorting issue, but perhaps I missed something subtle here.

Could you provide a specific example of where the issue is when using `mp_gga_relax_job`?

For the minimal example you shared, I get the same behavior for both ASE `Vasp` and quacc's patched `Vasp`, so it's difficult for me to see the precise issue you are referring to.

**Comment by zulissimeta** [comment]
This is a problem in the base VASP calculator too - the issue is that any INCAR settings that are per-species need to be specified in the same order as the species in the POSCAR that the VASP calculator will write (which is different than the base atoms object). 

The issue here is that if mp_gga_relax_job first attempts to guess the calc settings using the atoms object here:https://github.com/Quantum-Accelerators/quacc/blob/main/src/quacc/recipes/vasp/mp.py#L73

And then uses those as the defaults for the INCAR, even though the VASP calculator may swap the order. 

Adding something like this at the start of mp_gga_relax_job would fix the problem. 
```
srt, resrt = Vasp(atoms)._make_sort(atoms)
atoms = atoms[srt]
```

I think something like this would surface the issue (check the LDAUU INCAR setting vs the POSCAR)
```
from ase import Atoms
atoms = Atoms('FeOHFeO', cell=[10,10,10])
mp_gga_relax_job(atoms)
```

**Comment by Andrew-S-Rosen** [comment]
> the issue is that any INCAR settings that are per-species need to be specified in the same order as the species in the POSCAR that the VASP calculator will write (which is different than the base atoms object).

@zulissimeta: Uh, yikes!! That seems like a bug. I understand that the POSCAR atom ordering may differ from `Atoms`, but the fact that the atom-wise input parameters specified at calculator instantiation time need to match the ordering of the resulting POSCAR (rather than `Atoms`) is a huge issue! I think this isn't a problem with magnetic moments (right?) because those are attached as part of the `Atoms` object, but I suppose that the `Vasp` calculator has no knowledge about which input parameters are site-wise and which are not.

Okay, let me give this some thought.

**Comment by zulissimeta** [comment]
Yes, I believe your understanding about magmoms is correct. The calculator will sort the atoms object and then write, so I think they should be consistent.

**Comment by Andrew-S-Rosen** [comment]
Linking this to https://gitlab.com/ase/ase/-/issues/1596 for good measure.

**Comment by Andrew-S-Rosen** [comment]
Note: The sorting mechanism will not work as-is because LDAUU and LDAUJ are on a _per type_ basis, not a _per site_ basis like MAGMOM. For instance, if the POSCAR has `Fe Ni O` at the top, LDAUU would have three entries even if there are > 3 atoms in the POSCAR.
