### ISSUE TITLE
Should I have functions as default argument values?

### ISSUE THREAD

**Issue by arosen93** [Quantum-Accelerators/quacc#364]
@janosh, I have a question for you whenever you have a moment.

In some parts of my `quacc` package, I have classes where some of the default arguments are set to a function. An example is shown below (note: `mp_prerelax_job` and `mp_relax_job` are functions defined earlier in the code).

https://github.com/Quantum-Accelerators/quacc/blob/3ec7d8c704bc4494268360a961ce38a1e756a212/quacc/recipes/vasp/mp.py#L87-L111

My question for you is: is this okay to do? For instance, I'm well aware that having a `dict` or `list` as a default value for an argument is a bad idea because they're mutable. But do I have similar concerns with a function? And if so, is there a recommended way to avoid it (e.g. should I set the default as `None` and do the usual `self.prerelax_electron = prerelax_electron or mp_prerelax_job` like I usually do when the default is an empty `dict`?).

I _think_ what I have is okay, but I just want another person's input. If I had a class as the default argument, I imagine that would be problematic on its own.

**Comment by janosh** [comment]
I think it's fine. Python has no guarantees on immutability but people almost never mutate functions, and _if_ they do, hopefully they _really_ know what they're doing. Since the functions are defined in the module scope, they are parsed when that file is imported but not re-parsed until you start a new Python session. Any changes your class makes to these functions would accumulate every time you instantiate a class. Just to give a very contrived example:

```py
def foo():
    "doc str"
    return foo.__doc__

class C:
    def __init__(self, doc_func=foo):
        doc_func.__doc__ += 'some C-specific comment to always have no matter the doc_func'
        self.doc_str = doc_func()

C()
C().doc_str # double specific comment
>>> 'doc strsome C-specific comment to always have no matter the doc_funcsome C-specific comment to always have no matter the doc_func'
```

This problem wouldn't be fixed by doing the `None or mutable` construction either. For that, you would have to define the default function inside the class.

**Comment by arosen93** [comment]
Thank you!! This is super helpful :) makes sense!
