### ISSUE TITLE
Failing of `test_kpoint_schemes`

### ISSUE THREAD

**Issue by OmAximani0** [Quantum-Accelerators/quacc#865]
## Screenshot
![image](https://github.com/Quantum-Accelerators/quacc/assets/75031769/cdf2acce-877d-4e55-80f9-acd5fde7b9c6)

## Reference
https://github.com/Quantum-Accelerators/quacc/blob/f075db97fa22b3ffc09ecc0820e299e04cf2584c/tests/calculators/vasp/test_vasp.py#L642-L649

I think the `gamma` is by default set to `False` in `ase`. Link to :  [ase/calculators/vasp/create_input.py](https://gitlab.com/ase/ase/-/blob/master/ase/calculators/vasp/create_input.py#L1054)

**Comment by OmAximani0** [comment]
I tried the below approach and test are passing, If it's ok I can push the changes with PR #858 

```python
calc = Vasp(atoms, auto_kpts={"kppa": 1000})
assert calc.kpts == [10, 10, 10]
assert calc.input_params["gamma"] is False

atoms = bulk("Cu")
calc = Vasp(atoms, auto_kpts={"kppa": 1000}, gamma=True)
assert calc.kpts == [10, 10, 10]
assert calc.input_params["gamma"] is True
```

**Comment by arosen93** [comment]
@OmAximani0: Thank you for reporting.

I am a bit perplexed by this one, as the tests via the GitHub CI platform are passing. Additionally, when I run the specified test locally, my tests pass as well.

You are correct that `gamma` is `False` by default in the ASE `Vasp` calculator, but there's a subtlety here in that the `auto_kpts{"kppa": 1000}` kwarg calls the [`pymatgen.io.vasp.inputs.Kpoints.automatic_density` function](https://pymatgen.org/pymatgen.io.vasp.html#pymatgen.io.vasp.inputs.Kpoints.automatic_density), which can override the default value of `gamma` (which was the purpose of this test).

I did a significant refactor of the `quacc.calculators.vasp` module, so perhaps those changes are not reflected in your locally installed quacc version. I would recommend running `pip install -e .` and seeing if this resolves the tests. Either way, you can feel confident knowing that if the tests are passing on CI, your PR will be able to be merged.

Please let me know if there are any other subtleties that pop up related to this. I am going to close the issue for now since it doesn't seem to be an active issue, but I will re-open it if new evidence emerged.

**Comment by OmAximani0** [comment]
> @OmAximani0: Thank you for reporting.
> 
> I am a bit perplexed by this one, as the tests via the GitHub CI platform are passing. Additionally, when I run the specified test locally, my tests pass as well.
> 
> You are correct that `gamma` is `False` by default in the ASE `Vasp` calculator, but there's a subtlety here in that the `auto_kpts{"kppa": 1000}` kwarg can [override the default value](https://github.com/Quantum-Accelerators/quacc/blob/f075db97fa22b3ffc09ecc0820e299e04cf2584c/src/quacc/calculators/vasp.py#L625-L657) of `gamma` (which was the purpose of this test).
> 
> I did a significant refactor of the `quacc.calculators.vasp` module in #862, so perhaps those changes are not reflected in your locally installed quacc version. I would recommend running `pip install -e .` and seeing if this resolves the tests. Either way, you can feel confident knowing that if the tests are passing on CI, your PR will be able to be merged.
> 
> Please let me know if there are any other subtleties that pop up related to this. I am going to close the issue for now since it doesn't seem to be an active issue, but I will re-open it if new evidence emerged.

Thanks @arosen93 :smile:, The issue is resolved by reinstalling the dependencies!
